# Common Labels
labels:
  app: "assam"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "assam"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "selcohub/assam-ui"
  tag: multi-tenant-image-test-208afca1b9bfcd76e6be3891abfb0a522d43e34a
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/assam/"
  readinessProbePath: "/assam/"

env: |
  - name: PUBLIC_PATH
    value: /assam

    
extraVolumes: |
  - name: js-injection
    configMap:
      name: assam

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
