# Common Labels
labels:
  app: "meghalaya-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "meghalaya-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "selcohub/meghalaya-ui"
  tag: multi-tenant-image-test-208afca1b9bfcd76e6be3891abfb0a522d43e34a
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/meghalaya-ui/"
  readinessProbePath: "/meghalaya-ui/"

env: |
  - name: PUBLIC_PATH
    value: /meghalaya-ui

    
extraVolumes: |
  - name: js-injection
    configMap:
      name: meghalaya-ui

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
