creation_rules:
  - path_regex: environments/selco-dev-secrets.yaml$
    kms: arn:aws:kms:ap-south-1:654654556600:key/mrk-a84007bbb45e422b8dfd5ce979e415ce

  - path_regex: environments/selco-uat-secrets.yaml$
    kms: arn:aws:kms:ap-south-1:654654556600:key/mrk-3410e25f34924b8fb9dd03ee75e3ea4b
