apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  name: {{ include "ingress-nginx.fullname" . }}-kibana-login-plugin
  namespace: {{ include "ingress-nginx.namespace" . }}
data:
  main.lua: |-
{{ .Files.Get "files/kibana-login-plugin/main.lua" | indent 4 }}
