# Common Labels
labels:
  app: "processor-services"
  group: "rainmaker"

namespace: core-dev

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "processor-services"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m



# Container Configs
image:
  repository: "selcohub/processor-services"
  tag: "develop-61a468f4efec1a34aa45976ce546b33f209b21ff"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/processor-services/health"
  readinessProbePath: "/processor-services/health"
appType: "java-spring"
tracing-enabled: true
memory_limits: "2560Mi"
memory_requests: "2Gi"

lifecycle:
  postStart:
    exec:
      command:
        - sh
        - -c
        - |
          set -e
          apt-get update && apt-get install -y --no-install-recommends ffmpeg cpulimit
          ln -s /usr/bin/ffprobe /usr/local/bin/ffprobe   ##Symbolic link at different directory
          ln -s /usr/bin/ffmpeg /usr/local/bin/ffmpeg

# Additional Container Envs
env: |
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore

