# Common Labels
labels:
  app: "im-services"
  group: "rainmaker"

namespace: core-dev

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "im-services"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m


# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "im_service_schema"
    image:
      repository: "selcohub/im-services-db"
      tag: "develop-61a468f4efec1a34aa45976ce546b33f209b21ff"

# Container Configs
image:
  repository: "selcohub/im-services"
  tag: "develop-61a468f4efec1a34aa45976ce546b33f209b21ff"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/im-services/health"
  readinessProbePath: "/im-services/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx512m -Xms512m"
memory_limits: 1960Mi
cpu_limits: 1000m

lifecycle:
  postStart:
    exec:
      command:
        - sh
        - -c
        - |
          set -e
          apt update && apt install -y software-properties-common wget
          wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar -xf ffmpeg-release-amd64-static.tar.xz
          cd ffmpeg-*-amd64-static
          mv ffmpeg ffprobe /usr/local/bin/
# Additional Container Envs
env: |
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-mdms-service
        name: egov-service-host
  - name: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
    value: 100MB
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-user
        name: egov-service-host
  - name: EGOV_LOCATION_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-location
        name: egov-service-host
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-filestore
        name: egov-service-host
  - name: EGOV_FILESTORE_UPLOAD_ENDPOINT
    value: /filestore/v1/files
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-localization
        name: egov-service-host
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-workflow-v2
        name: egov-service-host
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-url-shortening
        name: egov-service-host
  - name: EGOV_URL_SHORTNER_ENDPOINT
    value: /egov-url-shortening/shortener
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-idgen
        name: egov-service-host
  - name: EGOV_IDGEN_PATH
    value: egov-idgen/id/_generate
  - name: WORKFLOW_CONTEXT_PATH
    value: egov-workflow-v2/egov-wf/businessservice/_search
  - name: MSEVA_MOBILE_APP_DOWNLOAD_LINK
    value: https://bit.ly/4e8qGJ3
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-hrms
        name: egov-service-host
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-im-services
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: JAVA_OPTS
    value: -Xmx512m -Xms512m
  - name: JAVA_ARGS
    value: -Dspring.profiles.active=monitoring
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"
