{{- with index .Values "secrets" "docker-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  .dockerconfigjson: {{ index . ".dockerconfigjson" | b64enc | quote }}
{{- end }}
