{{- with index .Values "secrets" "grafana-smtp" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  SMTP_USER: {{ .user | b64enc | quote }}
  SMTP_PASSWORD: {{ .password | b64enc | quote }}
{{- end }}
