{{- with index .Values "secrets" "loki-aws" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  accesskey: {{ .accesskey | b64enc | quote }}
  secretaccesskey: {{ .secretaccesskey | b64enc | quote }}
{{- end }}
