{{- with index .Values "secrets" "translator-service" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  GEMINI_API_KEY: {{ .GEMINI_API_KEY | b64enc | quote }}
{{- end }}
