# Common Labels
labels:
  app: "sikkim"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "sikkim"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "selcohub/sikkim-ui"
  tag: multi-tenant-image-test-208afca1b9bfcd76e6be3891abfb0a522d43e34a
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/sikkim/"
  readinessProbePath: "/sikkim/"

env: |
  - name: PUBLIC_PATH
    value: /sikkim

    
extraVolumes: |
  - name: js-injection
    configMap:
      name: sikkim

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
