# Common Labels
labels:
  app: "pdf-service"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "pdf-service"

initContainers:
  gitSync:
    enabled: true
    repo: "git@github.com:Selco-Foundation/configs.git"
    branch: "main"

# Container Configs
image:
  repository: "egovio/pdf-service"
  tag: pdf-2.9-lts-a17e8ebea8-48
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/pdf-service/health"
  readinessProbePath: "/pdf-service/health"
data-config-urls: "file:///work-dir/configs.git/pdf-service/data-config/bom.json"
format-config-urls: "file:///work-dir/configs.git/pdf-service/format-config/bom.json"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_LOCALISATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_FILESTORE_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_LOCALISATION_SEARCH
    value: /localization/messages/v1/_search
  - name: KAFKA_BROKER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: DEFAULT_LOCALISATION_TENANT
    value: "pg"
  - name: STATE_LEVEL_TENANT_ID
    value: "pg"
  - name: DATA_CONFIG_URLS
    value: {{ index .Values "data-config-urls" | quote }}
  - name: FORMAT_CONFIG_URLS
    value: {{ index .Values "format-config-urls" | quote }}