{{- define "common.hpa" -}}
  {{- if  .Values.hparam.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "common.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ template "common.name" . }}
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120  # 2 minutes for sustained high usage
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60  # Allow up to 100% increase in replicas per minute
    scaleDown:
      stabilizationWindowSeconds: 60  # 1 minute for sustained low usage
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60  # Allow up to 50% decrease in replicas per minute
  {{- end }}
  {{- end }}
