---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: amc-visit-scheduling
  namespace: core-dev
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: selcohub/amc-visit-scheduling:prod-08072026
              name: amc-visit-scheduling
          restartPolicy: OnFailure
  schedule: 15 11 * * *
  successfulJobsHistoryLimit: 1
  timeZone: Asia/Kolkata
