apiVersion: batch/v1
kind: CronJob
metadata:
  name: amc-visit-scheduling
  namespace: core-dev
spec:
  schedule: "15 11 * * *"
  timeZone: Asia/Kolkata
  successfulJobsHistoryLimit: 1
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: amc-visit-scheduling
            image: selcohub/amc-visit-scheduling:latest-2026-july-2
          restartPolicy: OnFailure
