apiVersion: batch/v1
kind: CronJob
metadata:
  name: carbon-emission-calculate
  namespace: core-dev
spec:
  schedule: "0 6 2 * *"
  timeZone: Asia/Kolkata
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: carbon-emission-calculate
            image: selcohub/cronjob-carbon-emission-calculate:prod-2026-08-19
          restartPolicy: OnFailure
