---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-escalation
  namespace: core-dev
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: selcohub/daily-escalation:latest-14112025
              name: daily-escalation
          restartPolicy: OnFailure
  schedule: 0 18 * * 1-6
  successfulJobsHistoryLimit: 1
  timeZone: Asia/Kolkata
