apiVersion: batch/v1
kind: CronJob
metadata:
  name: rms-mapping-sync
  namespace: core-dev
spec:
  schedule: "0 14 * * 0"
  timeZone: Asia/Kolkata
  successfulJobsHistoryLimit: 1
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rms-mapping-sync
            image: selcohub/rms-mapping-sync:latest-14012026
          restartPolicy: OnFailure
