# Common Labels
labels:
  app: "nagaland"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "nagaland"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "selcohub/nagaland-ui"
  tag: multi-tenant-image-test-208afca1b9bfcd76e6be3891abfb0a522d43e34a
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/nagaland/"
  readinessProbePath: "/nagaland/"

env: |
  - name: PUBLIC_PATH
    value: /nagaland

    
extraVolumes: |
  - name: js-injection
    configMap:
      name: nagaland

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
