name: translator
namespace: core-dev

# Common Labels
labels:
  app: "translator"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "translator"

# Container Configs
image:
  repository: "selcohub/translator-service"
  tag: develop-982680b9c22a824e29903a638774084085e43041
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/translator/health"
  readinessProbePath: "/translator/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"

persistence:
  enabled: false

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /translator
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: GEMINI_API_KEY
    valueFrom:
      secretKeyRef:
        name: translator-service
        key: GEMINI_API_KEY
