
spring.cloud.gateway.routes[0].id=asset-amc
spring.cloud.gateway.routes[0].uri=http://amc-service:8080/
spring.cloud.gateway.routes[0].predicates[0]=Path=/asset-amc/**

spring.cloud.gateway.routes[1].id=asset-registry
spring.cloud.gateway.routes[1].uri=http://asset-registry:8080/
spring.cloud.gateway.routes[1].predicates[0]=Path=/asset-registry/**

spring.cloud.gateway.routes[2].id=audit-service
spring.cloud.gateway.routes[2].uri=http://audit-service:8080/
spring.cloud.gateway.routes[2].predicates[0]=Path=/audit-service/**

spring.cloud.gateway.routes[3].id=boundary-service
spring.cloud.gateway.routes[3].uri=http://boundary-service:8080/
spring.cloud.gateway.routes[3].predicates[0]=Path=/boundary-service/**

spring.cloud.gateway.routes[4].id=access
spring.cloud.gateway.routes[4].uri=http://egov-accesscontrol:8080/
spring.cloud.gateway.routes[4].predicates[0]=Path=/access/**

spring.cloud.gateway.routes[5].id=egov-enc-service
spring.cloud.gateway.routes[5].uri=http://egov-enc-service:8080/
spring.cloud.gateway.routes[5].predicates[0]=Path=/egov-enc-service/**

spring.cloud.gateway.routes[6].id=filestore
spring.cloud.gateway.routes[6].uri=http://egov-filestore:8080/
spring.cloud.gateway.routes[6].predicates[0]=Path=/filestore/**

spring.cloud.gateway.routes[7].id=egov-hrms
spring.cloud.gateway.routes[7].uri=http://egov-hrms:8080/
spring.cloud.gateway.routes[7].predicates[0]=Path=/egov-hrms/**

spring.cloud.gateway.routes[8].id=egov-idgen
spring.cloud.gateway.routes[8].uri=http://egov-idgen:8080/
spring.cloud.gateway.routes[8].predicates[0]=Path=/egov-idgen/**

spring.cloud.gateway.routes[9].id=egov-indexer
spring.cloud.gateway.routes[9].uri=http://egov-indexer:8080/
spring.cloud.gateway.routes[9].predicates[0]=Path=/egov-indexer/**

spring.cloud.gateway.routes[10].id=localization
spring.cloud.gateway.routes[10].uri=http://egov-localization:8080/
spring.cloud.gateway.routes[10].predicates[0]=Path=/localization/**

spring.cloud.gateway.routes[11].id=egov-location
spring.cloud.gateway.routes[11].uri=http://egov-location:8080/
spring.cloud.gateway.routes[11].predicates[0]=Path=/egov-location/**

spring.cloud.gateway.routes[12].id=egov-mdms-service
spring.cloud.gateway.routes[12].uri=http://egov-mdms-service:8080/
spring.cloud.gateway.routes[12].predicates[0]=Path=/egov-mdms-service/**

spring.cloud.gateway.routes[13].id=otp
spring.cloud.gateway.routes[13].uri=http://egov-otp:8080/
spring.cloud.gateway.routes[13].predicates[0]=Path=/otp/**

spring.cloud.gateway.routes[14].id=user
spring.cloud.gateway.routes[14].uri=http://egov-user:8080/
spring.cloud.gateway.routes[14].predicates[0]=Path=/user/**

spring.cloud.gateway.routes[15].id=egov-workflow-v2
spring.cloud.gateway.routes[15].uri=http://egov-workflow-v2:8080/
spring.cloud.gateway.routes[15].predicates[0]=Path=/egov-workflow-v2/**

spring.cloud.gateway.routes[16].id=facility-service
spring.cloud.gateway.routes[16].uri=http://facility-service:8080/
spring.cloud.gateway.routes[16].predicates[0]=Path=/facility-service/**

spring.cloud.gateway.routes[17].id=field-planner
spring.cloud.gateway.routes[17].uri=http://field-planner:8080/
spring.cloud.gateway.routes[17].predicates[0]=Path=/field-planner/**

spring.cloud.gateway.routes[18].id=activity
spring.cloud.gateway.routes[18].uri=http://field-planner-activity:8080/
spring.cloud.gateway.routes[18].predicates[0]=Path=/activity/**

spring.cloud.gateway.routes[19].id=im-services
spring.cloud.gateway.routes[19].uri=http://im-services:8080/
spring.cloud.gateway.routes[19].predicates[0]=Path=/im-services/**

spring.cloud.gateway.routes[20].id=im-services-analytics
spring.cloud.gateway.routes[20].uri=http://im-services-analytics:8080/
spring.cloud.gateway.routes[20].predicates[0]=Path=/im-services-analytics/**

spring.cloud.gateway.routes[21].id=inbox
spring.cloud.gateway.routes[21].uri=http://inbox:8080/
spring.cloud.gateway.routes[21].predicates[0]=Path=/inbox/**

spring.cloud.gateway.routes[22].id=ingestion-service
spring.cloud.gateway.routes[22].uri=http://ingestion-service:8080/
spring.cloud.gateway.routes[22].predicates[0]=Path=/ingestion-service/**

spring.cloud.gateway.routes[23].id=pdf-service
spring.cloud.gateway.routes[23].uri=http://pdf-service:8080/
spring.cloud.gateway.routes[23].predicates[0]=Path=/pdf-service/**

spring.cloud.gateway.routes[24].id=processor-services
spring.cloud.gateway.routes[24].uri=http://processor-services:8080/
spring.cloud.gateway.routes[24].predicates[0]=Path=/processor-services/**

spring.cloud.gateway.routes[25].id=translator
spring.cloud.gateway.routes[25].uri=http://translator:8080/
spring.cloud.gateway.routes[25].predicates[0]=Path=/translator/**

spring.cloud.gateway.routes[26].id=user-otp
spring.cloud.gateway.routes[26].uri=http://user-otp:8080/
spring.cloud.gateway.routes[26].predicates[0]=Path=/user-otp/**

spring.cloud.gateway.routes[27].id=vendor
spring.cloud.gateway.routes[27].uri=http://vendor-registry:8080/
spring.cloud.gateway.routes[27].predicates[0]=Path=/vendor/**
