# Common Labels
labels:
  app: "test-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "test-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "selcohub/test-ui"
  tag: multi-tenant-image-test-9bc22167ff18f0666750167a866323bb08ba81d0
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/test-ui/"
  readinessProbePath: "/test-ui/"
    
extraVolumes: |
  - name: js-injection
    configMap:
      name: test-ui

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
