version: v.0.3
modules:
  - name: backbone-dev
    services:
      - kafka-kraft
      - elasticsearch-data
      - elasticsearch-master
      - kibana
      - cert-manager
      - ingress-nginx
      - minio
      - playground
      - redis
  - name: core-dev
    dependencies:
      - "backbone-dev"
    services:
#      nagaland:
#      mizoram:
#      egov-hrms: court-room-hrm-changes-691901a842-14
#      egov-filestore: core-2.9-lts-mvn-check-17b905d01d-13
#      egov-workflow-v2: core-2.9-lts-mvn-check-07ed8e9a49-12
#      im-services: gateway-filestore-fix-ebbd0c4cd8-24
#      digit-ui: v1.0.0-713a7b9848eaffa417160d38151c0efa51ce314b
#      inbox: v1.0.0-d31bfc0d253ea5056c319cd71cecaef125bc3aea
      egov-mdms-service: core-2.9-lts-mvn-check-c33cfe45ab-12
      egov-notification-sms: egov-notification-sms:master-03072024-1
      audit-service: core-2.9-lts-mvn-check-c33cfe45ab-9
      egov-accesscontrol: core-2.9-lts-mvn-check-34362a8b87-9
      egov-enc-service: core-2.9-lts-mvn-check-c607f2d4de-20
      egov-idgen: egov-idgen:main-03072024-1
      egov-indexer: core-2.9-lts-mvn-check-5f0cc52126-55
      egov-localization: core-2.9-lts-mvn-check-59c2e5ea5b-9
      egov-location: core-2.9-lts-mvn-check-c33cfe45ab-9
      egov-otp: core-2.9-lts-mvn-check-72333e5530-5
      egov-persister: core-2.9-lts-mvn-check-c33cfe45ab-7
      egov-user: core-2.9-lts-egov-user-deployement-c33cfe45ab-13
      gateway: gateway-2.9.3-56a8630218-44
      im-services-analytics: im-services-analytics-27624fe645-11
      user-otp: core-2.9-lts-mvn-check-15fe7099b6-7
