global:
  domain:  e4h-dev.selcofoundation.org
root-ingress:
  cert-issuer: "letsencrypt-prod"
configmaps:
  egov-config:
    data:
      db-host: "selco-prod-db.c1yks4g2c2zp.ap-south-1.rds.amazonaws.com" ## Add db-host name eg: egov-demo.database.azure.com
      db-name: "selcodevdb" ## Add db-name
      db-url: "jdbc:postgresql://selco-prod-db.c1yks4g2c2zp.ap-south-1.rds.amazonaws.com/selcodevdb"
      es-host: "elasticsearch-data.backbone-dev"
      es-indexer-host: "https://elasticsearch-data.backbone-dev:9200/"
      kafka-brokers: "kafka-kraft-controller-headless.backbone-dev:9092"
      egov-services-fqdn-name: https://e4h-dev.selcofoundation.org/
egov-user:
  replicas: 1
  heap: "-Xmx256m -Xms256m"
  memory_limits: 512Mi
  otp-validation: "true"
  citizen-otp-enabled: "true"
  employee-otp-enabled: "false"
  access-token-validity: 10080
  refresh-token-validity: 20160
  default-password-expiry: 90
  mobile-number-validation: "false"
  roles-state-level: "true"
  citizen-registration-withlogin: "true"
  citizen-otp-fixed: "123456"
  citizen-otp-fixed-enabled: "true"
  egov-state-level-tenant-id: "in"
  decryption-abac-enabled: "true"

egov-accesscontrol:
  replicas: 1

digit-ui:
  replicas: 1
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://selco-assets.s3.ap-south-1.amazonaws.com/globalConfigs.js type=text/javascript></script>
      ';"

meghalaya:
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://selco-assets.s3.ap-south-1.amazonaws.com/meghalayaGlobalConfig.js type=text/javascript></script>
      ';"    

nagaland:
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://selco-assets.s3.ap-south-1.amazonaws.com/nagalandGlobalConfig.js type=text/javascript></script>
      ';"    

assam:
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://selco-assets.s3.ap-south-1.amazonaws.com/assamGlobalConfig.js type=text/javascript></script>
      ';"    

manipur:
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://selco-assets.s3.ap-south-1.amazonaws.com/manipurGlobalConfig.js type=text/javascript></script>
      ';"    

mizoram:
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://selco-assets.s3.ap-south-1.amazonaws.com/mizoramGlobalConfig.js type=text/javascript></script>
      ';"    

odisha:
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://selco-assets.s3.ap-south-1.amazonaws.com/odishaGlobalConfig.js type=text/javascript></script>
      ';"    

sikkim:
  custom-js-injection: |
    sub_filter.conf: "
      sub_filter  '<head>' '<head>
      <script src=https://selco-assets.s3.ap-south-1.amazonaws.com/sikkimGlobalConfig.js type=text/javascript></script>
      ';"    

egov-filestore:
  replicas: 1
  memory_limits: "712Mi"
  heap: "-Xmx512m -Xms512m"
  volume: /opt/eGov/filestore
  is-bucket-fixed: "true"
  minio.url : "http://minio.backbone:9000/"
  aws.s3.url : "https://s3.amazonaws.com"
  is-s3-enabled: "true"
  minio-enabled: false
  allowed-file-formats-map: '{json:{''application/json'',''text/plain'',''application/geo+json''},jpg:{''image/jpg'',''image/jpeg''},jpeg:{''image/jpeg'',''image/jpg''},png:{''image/png''},pdf:{''application/pdf''},odt:{''application/vnd.oasis.opendocument.text''},ods:{''application/vnd.oasis.opendocument.spreadsheet''},docx:{''application/x-tika-msoffice'',''application/x-tika-ooxml'',''application/vnd.oasis.opendocument.text'',''application/msword'',''application/vnd.openxmlformats-officedocument.wordprocessingml.document''},doc:{''application/x-tika-msoffice'',''application/x-tika-ooxml'',''application/vnd.oasis.opendocument.text'',''application/msword''},dxf:{''text/plain'',''application/dxf'',''application/octet-stream'',''image/vnd.dxf'',''image/vnd.dxf;format=ascii'',''image/vnd.dxf;format=binary'',''image/vnd.dxb''},csv:{''text/plain'',''text/csv'',''application/zip''},txt:{''text/plain''},xlsx:{''application/x-tika-ooxml'',''application/x-tika-msoffice'',''application/vnd.ms-excel'',''application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'',''application/zip''},xls:{''application/x-tika-ooxml'',''application/x-tika-msoffice'',''application/vnd.ms-excel''},mp4:{"video/mp4", "video/quicktime"},mp3:{"audio/mpeg"},avi:{"video/x-msvideo"},mov:{"video/quicktime"}, wmv:{"video/x-ms-wmv"},m3u8:{"application/vnd.apple.mpegurl","application/x-mpegURL"},ts:{"video/MP2T","video/mp2t", "application/octet-stream"}}'
  allowed-file-formats: "jpg,jpeg,png,doc,docx,pdf,odt,ods,text,dxf,xls,xlsx"
  filestore-url-validity: 3600
  fixed-bucketname: selco-dev  ## Add filestore bucket name

egov-enc-service:
  heap: "-Xmx256m -Xms256m"
  memory_limits: 512Mi
  state-level-tenant-id: "pb"

egov-idgen:
  idformat-from-mdms: "true"
  java-args: -Dspring.profiles.active=monitoring
  heap: "-Xmx192m -Xms192m"
  autocreate-new-seq: "true"

egov-localization:
  replicas: 1
  heap: "-Xmx256m -Xms256m"
  memory_limits: 512Mi

egov-workflow-v2:
  replicas: 1

egov-hrms:
  replicas: 1

egov-notification-sms:
  sms-provider-url: "sms provider url" ## Add sms provider url
  sms.provider.class: "Console"
  sms.provider.contentType:  "application/x-www-form-urlencoded"
  sms-config-map: "{'User':'$username', 'passwd': '$password', 'sid':'$senderid', 'mobilenumber':'$mobileno', 'message':'$message', 'mtype':'N', 'DR':'N', 'smsservicetype':'singlemsg'}"
  sms-gateway-to-use: "sms provider name" ## Add sms provider name
  sms-sender: "sms sender" ## Add sms sender
  sms-sender-requesttype: "GET"
  sms-custom-config: "true"
  sms-extra-req-params: "mtype=N&DR=Y"
  sms-sender-req-param-name: "sid"
  sms-sender-username-req-param-name: "User"
  sms-sender-password-req-param-name: "passwd"
  sms-destination-mobile-req-param-name: "mobilenumber"
  sms-message-req-param-name: "message"
  sms-error-codes: "401,403,404,405,406,407,408,409,410,411,412,413,414"
egov-mdms-service:
  memory_limits: "1812Mi"
  replicas: 1
  images:
    - egovio/egov-mdms-service:core-2.9-lts-mvn-check-c33cfe45ab-12
  mdms-path: "/work-dir/egov-mdms-data/data"
  initContainers:
    gitSync:
      repo: "git@github.com:Selco-Foundation/egov-mdms-data"
      branch: "develop"
  mdms-folder: "egov-mdms-data"
  masters-config-url: "file:///work-dir/egov-mdms-data/master-config.json"
  java-args: -Dspring.profiles.active=monitoring

egov-indexer:
  replicas: 1
  heap: "-Xmx512m -Xms512m"
  memory_limits: "768Mi"
  initContainers:
    gitSync:
      repo: "git@github.com:Selco-Foundation/configs"        ##### Change repo url with Your fork Repo url
      branch: "main"                                         ##### Change repo branch with Your fork Repo branch
  egov-indexer-yaml-repo-path: "file:///work-dir/configs/egov-indexer/im-services.yml,file:///work-dir/configs/egov-indexer/privacy-audit.yaml,file:///work-dir/configs/egov-indexer/egov-url-shortening-indexer.yaml,file:///work-dir/configs/works/egov-indexer/individual-indexer.yml"

egov-persister:
  replicas: 1
  heap: "-Xmx256m -Xms256m"
  memory_limits: 512Mi
  images:
    - egovio/egov-persister:core-2.9-lts-mvn-check-c33cfe45ab-7
  persist-yml-path: "file:///work-dir/configs/egov-persister/egov-user-event-persister.yml,file:///work-dir/configs/egov-persister/egov-workflow-v2-persister.yml,file:///work-dir/configs/egov-persister/im-services-persister.yml,file:///work-dir/configs/egov-persister/hrms-employee-persister.yml,file:///work-dir/configs/egov-persister/mdms-persister.yml,file:///work-dir/configs/egov-persister/audit-service-persister.yml,file:///work-dir/configs/egov-persister/privacy-audit.yml"
  initContainers:
    gitSync:
      repo: "git@github.com:Selco-Foundation/configs"      ##### Change repo url with Your fork Repo url
      branch: "main"

audit-service:
  replicas: 1
  persist-yml-path: "https://raw.githubusercontent.com/egovernments/configs/UNIFIED-DEV/works/egov-persister/attendance-service-persister.yml,https://raw.githubusercontent.com/egovernments/configs/UNIFIED-DEV/works/egov-persister/muster-service-persister.yml,https://raw.githubusercontent.com/egovernments/configs/UNIFIED-DEV/works/egov-persister/estimate-service.yml,https://raw.githubusercontent.com/egovernments/configs/UNIFIED-DEV/works/egov-persister/contract-service-persister.yml,https://raw.githubusercontent.com/egovernments/configs/UNIFIED-DEV/works/egov-persister/bankaccounts-persister.yml,https://raw.githubusercontent.com/egovernments/configs/UNIFIED-DEV/works/egov-persister/expense-bill-payment-persister.yaml"
  initContainers:
    gitSync:
      repo: "git@github.com:Selco-Foundation/configs"
      branch: "main"
