# Common Labels
labels:
  app: "manipur"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "manipur"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "selcohub/manipur-ui"
  tag: multi-tenant-image-test-208afca1b9bfcd76e6be3891abfb0a522d43e34a
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/manipur/"
  readinessProbePath: "/manipur/"

env: |
  - name: PUBLIC_PATH
    value: /manipur

    
extraVolumes: |
  - name: js-injection
    configMap:
      name: manipur

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
