name: DIGIT-Install workflow for Dev
on:
  push:
    branches:
      - Deploy
      - Deploy-UAT
  workflow_dispatch:
  repository_dispatch:

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    outputs:
      deploy-as-code-changed: ${{ steps.check_files.outputs.deploy-as-code-changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in deploy-as-code
        id: check_files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            deploy-as-code/**

  DIGIT-deployment:
    runs-on: ubuntu-latest
#    env:
#      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      AWS_REGION:  ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ env.CLUSTER_NAME_DEV }}
          cat ~/.kube/config > kubeconfig

      - name: Creating namespace
        run: kubectl create namespace egov
        continue-on-error: true

      - name: Install kubectl in runner
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest' # default is latest stable
        id: install

      - name: Verfiy kubectl get nodes
        run: |
          kubectl get nodes

      - name: Install sops
        run: |
          sudo apt update
          wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
          chmod +x sops-v3.7.1.linux
          sudo mv sops-v3.7.1.linux /usr/local/bin/sops

      - name: sops decryption
        run: |
          sudo sops --decrypt --kms ${{ env.PUBLIC_KMS_KEY_DEV }} $HOME/work/DIGIT-DevOps/DIGIT-DevOps/deploy-as-code/charts/environments/selco-dev-secrets.yaml > env-secrets1.yaml
          cp env-secrets1.yaml $HOME/work/DIGIT-DevOps/DIGIT-DevOps/deploy-as-code/charts/environments/selco-dev-secrets.yaml
      # working-directory: deploy-as-code/charts/environments


      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest' # Specify the version of Helm

      - name: Install Helmfile
        uses: helmfile/helmfile-action@v1.9.0
        with:
          helmfile-version: 'v0.150.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff

      - name: Commit Id for Latest Deployment
        run: |
          git clone https://github.com/Selco-Foundation/E4H_Digital_Platform.git
          cd E4H_Digital_Platform
          git checkout develop
          digit-ui_commit=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "digit-ui_commit=$digit-ui_commit" >> $GITHUB_ENV
          filestore_commit=$(git log -1 --pretty=format:%H -- backend/core-services/egov-filestore)
          echo "filestore_commit=$filestore_commit" >> $GITHUB_ENV
          hrms_commit=$(git log -1 --pretty=format:%H -- backend/business-services/egov-hrms)
          echo "hrms_commit=hrms_commit" >> $GITHUB_ENV
          im-Services_commit=$(git log -1 --pretty=format:%H -- backend/municipal-services/im-services)
          echo "im-Services_commit=$im-Services_commit" >> $GITHUB_ENV
          inbox_commit=$(git log -1 --pretty=format:%H -- backend/municipal-services/inbox)
          echo "inbox_commit=inbox_commit" >> $GITHUB_ENV
          workflow-v2_commit=$(git log -1 --pretty=format:%H -- backend/core-services/egov-workflow-v2)
          echo "workflow-v2_commit=$workflow-v2_commit" >> $GITHUB_ENV 

#      - name: digit deployment
#        run: helmfile -f digit-helmfile.yaml apply --include-needs=true\
#          --set scheduler.initContainers.dbMigration.image.tag=develop-${{ env.scheduler_commit }} \
#          --set payment-calculator.image.tag=develop-${{ env.payment_calculator_commit }} \
#          --set payment-calculator.initContainers.dbMigration.image.tag=develop-${{ env.payment_calculator_commit }} \
#          --set im-services.image.tag=develop-${{ env.im-Services_commit }} \
#          --set scheduler.initContainers.dbMigration.image.tag=develop-${{ env.scheduler_commit }} \
#          --set payment-calculator.image.tag=develop-${{ env.payment_calculator_commit }} \
#          --set payment-calculator.initContainers.dbMigration.image.tag=develop-${{ env.payment_calculator_commit }} \
#          --set digit-ui.image.tag=develop-${{ env.digit_ui_commit }} \
#          --set dristi-case-pdf.image.tag=develop-${{ env.dristi_case_pdf_commit }} \
#        working-directory: deploy-as-code
#        env:
#          HELMFILE_ENV: "solutions-dev"



