name: DIGIT-Install workflow for UAT
on:
#  push:
#    branches:
#      - Deploy
#      - Deploy-UAT
  workflow_dispatch:
  repository_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    outputs:
      deploy-as-code-changed: ${{ steps.check_files.outputs.deploy-as-code-changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in deploy-as-code
        id: check_files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            deploy-as-code/**

  DIGIT-deployment:
    runs-on: ubuntu-latest
    #    env:
    #      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
    #      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #      AWS_REGION:  ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ vars.CLUSTER_NAME_UAT }}
          cat ~/.kube/config > kubeconfig

      - name: Creating namespace
        run: kubectl create namespace egov
        continue-on-error: true

      - name: Install kubectl in runner
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest' # default is latest stable
        id: install

      - name: Verfiy kubectl get nodes
        run: |
          kubectl get nodes

      - name: Install sops
        run: |
          sudo apt update
          wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
          chmod +x sops-v3.7.1.linux
          sudo mv sops-v3.7.1.linux /usr/local/bin/sops

      - name: sops decryption
        run: |
          aws sts get-caller-identity
          sops --decrypt --kms ${{ secrets.PUBLIC_KMS_KEY_UAT }} $HOME/work/DIGIT-DevOps/DIGIT-DevOps/deploy-as-code/charts/environments/selco-uat-secrets.yaml > env-secrets1.yaml
          cp env-secrets1.yaml $HOME/work/DIGIT-DevOps/DIGIT-DevOps/deploy-as-code/charts/environments/selco-uat-secrets.yaml
      # working-directory: deploy-as-code/charts/environments


      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest' # Specify the version of Helm

      - name: Install Helmfile
        uses: helmfile/helmfile-action@v1.9.0
        with:
          helmfile-version: 'v0.150.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff

      - name: Commit Id for Latest Deployment
        run: |
          git clone https://github.com/Selco-Foundation/E4H_Digital_Platform.git
          cd E4H_Digital_Platform
          git checkout main
          digit_ui_commit=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "digit_ui_commit=$digit_ui_commit" >> $GITHUB_ENV
          filestore_commit=$(git log -1 --pretty=format:%H -- backend/core-services/egov-filestore)
          echo "filestore_commit=$filestore_commit" >> $GITHUB_ENV
          hrms_commit=$(git log -1 --pretty=format:%H -- backend/business-services/egov-hrms)
          echo "hrms_commit=$hrms_commit" >> $GITHUB_ENV
          im_Services_commit=$(git log -1 --pretty=format:%H -- backend/municipal-services/im-services)
          echo "im_Services_commit=$im_Services_commit" >> $GITHUB_ENV
          inbox_commit=$(git log -1 --pretty=format:%H -- backend/municipal-services/inbox)
          echo "inbox_commit=$inbox_commit" >> $GITHUB_ENV
          workflow_v2_commit=$(git log -1 --pretty=format:%H -- backend/core-services/egov-workflow-v2)
          echo "workflow_v2_commit=$workflow_v2_commit" >> $GITHUB_ENV 
          nagaland_commit=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "nagaland_commit=$nagaland_commit" >> $GITHUB_ENV
          assam_commit=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "assam_commit=$assam_commit" >> $GITHUB_ENV
          manipur_commit=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "manipur_commit=$manipur_commit" >> $GITHUB_ENV
          mizoram_commit=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "mizoram_commit=$mizoram_commit" >> $GITHUB_ENV
          odisha_commit=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "odisha_commit=$odisha_commit" >> $GITHUB_ENV
          sikkim_commit=$(git log -1 --pretty=format:%H -- frontend/micro-ui)
          echo "sikkim_commit=$sikkim_commit" >> $GITHUB_ENV

      - name: digit deployment
        run: |
          helmfile -f digit-helmfile.yaml apply --include-needs=true\
            --set nagaland.image.tag=main-${{ env.nagaland_commit }} \
            --set digit-ui.image.tag=main-${{ env.digit_ui_commit }} \
            --set im-services.image.tag=main-${{ env.im_Services_commit }} \
            --set im-services.initContainers.dbMigration.image.tag=main-${{ env.im_Services_commit }} \
            --set assam.image.tag=main-${{ env.assam_commit }} \
            --set sikkim.image.tag=main-${{ env.sikkim_commit }} \
            --set manipur.image.tag=main-${{ env.manipur_commit }} \
            --set mizoram.image.tag=main-${{ env.mizoram_commit }} \
            --set odisha.image.tag=main-${{ env.odisha_commit }} \
            --set inbox.image.tag=main-${{ env.inbox_commit }} \
            --set inbox.initContainers.dbMigration.image.tag=main-${{ env.inbox_commit }} \
#            --set egov-hrms.image.tag=main-${{ env.hrms_commit }} \
#            --set egov-hrms.initContainers.dbMigration.image.tag=main-${{ env.hrms_commit }} \
#            --set egov-filestore.image.tag=main-${{ env.filestore_commit }} \
#            --set egov-filestore.initContainers.dbMigration.image.tag=main-${{ env.filestore_commit }} \
#            --set egov-workflow-v2.image.tag=main-${{ env.workflow_v2_commit }} \
#            --set egov-workflow-v2.initContainers.dbMigration.image.tag=main-${{ env.workflow_v2_commit }} \
        working-directory: deploy-as-code
        env:
          HELMFILE_ENV: "selco-uat"



